### ISSUE TITLE
Execution fail on Debian Unstable

### ISSUE THREAD

**Issue by russel** [gak/pycallgraph#123]
Debian Unstable has a Python 2 package python-pycallgraph and this appears to install and work fine, but only for Python 2 codes. There appears to be no python3-pycallgraph, at least as yet. I therefore installed into my Python3 installation with "pip3 install pycallgraph". Installation appears fine and I get the newly installed Python 3 executed script before package installed one, i.e. /usr/local/bin/pycallgraph is what is executed for me now. Sadly though:

```
Traceback (most recent call last):
  File "/usr/local/bin/pycallgraph", line 17, in <module>
    __config = __pycallgraph.Config()
AttributeError: 'module' object has no attribute 'Config'
```

**Comment by gak** [comment]
Hi @russel sorry for the extremely slow reply. I realise you probably won't have this set up any more, but for future users of this problem I will respond anyway:

I am unsure about why this is happening. I would suggest un-installing python-pycallgraph and ensuring the minimal requirements for the Python version is installed (3.3+).

If that doesn't work, I suggest trying it in a virtual environment using venv or pyenv, etc.

Closing for now.
