### ISSUE TITLE
problem running 

### ISSUE THREAD

**Issue by saeed-tu** [gak/pycallgraph#139]
Hi there,

I'm trying to learn how to get in work pycallgraph on my mac os,
I just tried to run the basic example below but I receive error code 5 without any details on it, can u pls let me know what this error could mean?
code:
```
from pycallgraph import PyCallGraph
from pycallgraph.output import GraphvizOutput
from banana import Banana

graphviz = GraphvizOutput(output_file='filter_none.png')

with PyCallGraph(output=graphviz):
    banana = Banana()
    banana.chew()
```
error message:
pycallgraph.exceptions.PyCallGraphException: The command "dot -Tpng -ofilter_none.png /var/folders/74/bn7qblyj2ys_br8_y10zy4xc0000gn/T/tmprVNnRz" failed with error code 5.

**Comment by gak** [comment]
Make sure graphviz is installed.

You can test this by going into your command line and running "dot".
