### ISSUE TITLE
(suggestion) add high res png output to graphviz

### ISSUE THREAD

**Issue by techbliss** [gak/pycallgraph#152]
I don't see very good 
and it do not help that graphviz default dpi is 96 
when having many nodes and you have to zoom in , its very blurred.
maybe add a higher dpi so you have to zoom out a little instead of zooming in

graphviz.py
adding this to the command scale the png(fill) and  set resolution much higher(dpi), so when zooming in the png its more readable

maybe have resolution's as a extra command option ?

```
    def done(self):
    source = self.generate()

    self.debug(source)

    fd, temp_name = tempfile.mkstemp()
    with os.fdopen(fd, 'w') as f:
        f.write(source)

    cmd = '"{0}" -T{1} -Gdpi=800 -Gratio=fill -o{2} {3}'.format(
        self.tool, self.output_type, self.output_file, temp_name
```

**Comment by techbliss** [comment]
well dev didn't answer in two years, closing issue

**Comment by Vedaad-Shakib** [comment]
:(

**Comment by krstp** [comment]
I hope this topic comes back.
